### ISSUE TITLE
UnboundLocalError: local variable 'adj_url' referenced before assignment

### ISSUE THREAD

**Issue by skhiggins** [skhiggins/PythonTools#15]
<https://github.com/skhiggins/PythonTools/blob/b885dfffa0556c460b1f3d4282129f98c282368c/get_files.py#L60-L66>
When `longer_url.startswith('http://')`, the condition `if not longer_url.startswith('http://'):` is false, so then the code never defines `adj_url` before getting to the line `if adj_url.endswith('zip'):`

**Comment by angelynaye** [comment]
Fixed in newest pull request #17
