### ISSUE TITLE
Add a `contains` option

### ISSUE THREAD

**Issue by skhiggins** [skhiggins/PythonTools#22]
This option would only download files that contain a certain string. For example, <http://portafolioinfo.cnbv.gob.mx/PortafolioInformacion/> has a lot of xlsx files; suppose that in addition to specifying `Type = 'xlsx'` we want to specify to only download files with `BM_` in the filename. Then the user should be able to specify the option `contains = 'BM_'`. They should also be able to specify a list e.g. `contains = ['BM_', 'BD_']`.

If this option is not specified, all files with the extensions specified in `Type` would be downloaded, as they are now.

**Comment by angelynaye** [comment]
fixed in f0bb221
