### ISSUE TITLE
Error downloading, adds urlbase to the front and keeps full url after that

### ISSUE THREAD

**Issue by skhiggins** [skhiggins/PythonTools#23]
See some of the output messages in the last cell of output in <https://github.com/skhiggins/PythonTools/blob/master/tests/scrape_cnbv.ipynb>, for example the following message:
```
error downloading https://www.gob.mx/https://www.gob.mx/cms/uploads/attachment/file/121760/CUB_R03_J_y_R27_B-2711_Servicios_de_Inversion_Vigencia_201401-actual_Actualizacion_31_Agosto_2015.pdf
```

**Comment by angelynaye** [comment]
fixed in commit: "fd98f91", See get_files_test_repetitive_urlbase_front .ipynb
