### ISSUE TITLE
Special case: page source doesn't contain files but Inspect Element does

### ISSUE THREAD

**Issue by skhiggins** [skhiggins/PythonTools#27]
Some pages have javascript in the page source but do not list the files. For example, if you go to <http://www.beta.inegi.org.mx/proyectos/encestablecimientos/especiales/enaproce/2015/> and View Page Source, there are no .pdf, .xlsx, etc., so if you try to `get_files()` it will not download anything. However, if you Inspect Element on the same page, there are .pdf, .xlsx, etc. Is there a way to get Beautiful Soup to go behind the javascript in the page source and realize that there are files here?

**Comment by angelynaye** [comment]
Solved in #35
