### ISSUE TITLE
Selenium code: chromedriver and overwrite=False

### ISSUE THREAD

**Issue by skhiggins** [skhiggins/PythonTools#33]
- [x] chromedriver issue:
The chromedriver might be specific to the user and there is comment in get_files where the user would have to change the code:
https://github.com/skhiggins/PythonTools/blob/eca094e96135a92c290fd6ab58dca1375c3259e8/get_files.py#L51-L52
However, we want the user to be able to set the folder for their chromedriver without editing the get_files.py file. Hence, we should add a chromedriver option where they set the filepath. The default could be what you have it set as now, if that's the default place for it on Macs.

- [x] More user friendly chromedriver error:
See the error I got in [get_files_test_selenium.ipynb](https://github.com/skhiggins/PythonTools/blob/master/tests/get_files_test_selenium.ipynb). Once the above is fixed I'll try to run it without getting an error, but in any case we should have a more user-friendly error (for example the user might not have realized that their scrape was going to require Selenium). The error should explain that the site they are scraping contains files that can only be scraped using Selenium, which requires Chromedriver, and should provide a link to https://sites.google.com/a/chromium.org/chromedriver/home, and say that the location of the driver should then be specified using the option you add in response to the last point.

- [x] `overwrite=False`
It looks like the `overwrite=False` option is not working in [get_files_test_selenium.ipynb](https://github.com/skhiggins/PythonTools/blob/master/tests/get_files_test_selenium.ipynb). See the last block of code, where above it I successfully downloaded a bunch of pdf's before getting an error, but then when I run the same command with `overwrite=False` it re-downloads the same pdf's rather than giving me the message that they're already downloaded.

**Comment by angelynaye** [comment]
Solved in #35
