### ISSUE TITLE
Some pdfs get error downloading, not sure why

### ISSUE THREAD

**Issue by skhiggins** [skhiggins/PythonTools#7]
Try downloading the pdf files from <http://www.inegi.org.mx/est/contenidos/espanol/proyectos/censos/ce2009/cuestionarios.asp> using `get_files()`. I'm getting an error for every file, but they don't have spaces in the names so this is some other issue.

**Comment by angelynaye** [comment]
fixed in the commit "dccf913", See "get_files_test_weird_download_error .ipynb"
